package ${entity.filePackage};

import org.springframework.stereotype.Repository;
<#list entity.imports as import>
import ${import};
</#list>

/**
 * This code is generated by FreeMarker
 */
@Repository
public interface ${entity.entityName}Mapper{

     void insert(${entity.entityName}PO ${entity.objectName});

}
