package ${entity.filePackage};

<#list entity.imports as import>
import ${import};
</#list>

/**
 * This code is generated by FreeMarker
 */

public interface ${entity.entityName}Service{
     void insert(${entity.entityName}PO ${entity.objectName});
}
